Instruction: Choose a dataset and perform a data storytelling, choose the proper data visualization, do not use words, your graphs must tell a story.

In [28]:
import pandas as pd
import matplotlib.pyplot as plt
dir = "tic-tac-toe.data"
df =  pd.read_csv(dir, sep=",")

# corr_matrix = df.query('win == 1').corr()
# corr_matrix["win"]

df.query('win == 0').describe()

,a,b,c,d,e,f,g,h,i,win
count,332.000000,332.000000,332.000000,332.000000,332.000000,332.000000,332.000000,332.000000,332.000000,332.0
mean,-0.069277,0.156627,-0.069277,0.156627,-0.301205,0.156627,-0.069277,0.156627,-0.069277,0.0
std,0.898819,0.861839,0.898819,0.861839,0.875790,0.861839,0.898819,0.861839,0.898819,0.0
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.0
25%,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.0
50%,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.0
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0

In [20]:
# import module
from tabulate import tabulate
 
# assign data
mydata = [
    [str(int(corr_matrix["win"].a*100+50)) + "%", str(int(corr_matrix["win"].b*100+50)) + "%", str(int(corr_matrix["win"].c*100+50)) + "%"], 
    [str(int(corr_matrix["win"].e*100+50)) + "%", str(int(corr_matrix["win"].e*100+50)) + "%", str(int(corr_matrix["win"].f*100+50)) + "%"], 
    [str(int(corr_matrix["win"].e*100+50)) + "%", str(int(corr_matrix["win"].e*100+50)) + "%", str(int(corr_matrix["win"].e*100+50)) + "%"]
]
 
# display table
print(tabulate(mydata, tablefmt="grid"))

+------------+----------------------+------------+
|  0.128689  | -0.09039131293252291 |  0.128689  |
+------------+----------------------+------------+
| -0.0903913 | 84%                  | -0.0903913 |
+------------+----------------------+------------+
|  0.128689  | -0.09039131293252285 |  0.128689  |
+------------+----------------------+------------+