Instruction: Choose a dataset and perform a data storytelling, choose the proper data visualization, do not use words, your graphs must tell a story.

In [28]:
import pandas as pd
import matplotlib.pyplot as plt
dir = "../tic-tac-toe.data"
df =  pd.read_csv(dir, sep=",")

corr_matrix = df.corr()


df.describe()

,a,b,c,d,e,f,g,h,i,win
count,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000,958.000000
mean,0.086639,0.050104,0.086639,0.050104,0.123173,0.050104,0.086639,0.050104,0.086639,0.653445
std,0.882791,0.858661,0.882791,0.858661,0.904803,0.858661,0.882791,0.858661,0.882791,0.476121
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [29]:
# import module
from tabulate import tabulate
 
# assign data
mydata = [
    [corr_matrix["win"].a, corr_matrix["win"].b, corr_matrix["win"].c], 
    [corr_matrix["win"].d, corr_matrix["win"].e, corr_matrix["win"].f], 
    [corr_matrix["win"].g, corr_matrix["win"].h, corr_matrix["win"].i]
]
 
# display table
print("chances of winning based on placement")
print(tabulate(mydata, tablefmt="grid"))

chances of winning based on placement
+------------+------------+------------+
|  0.128689  | -0.0903913 |  0.128689  |
+------------+------------+------------+
| -0.0903913 |  0.341749  | -0.0903913 |
+------------+------------+------------+
|  0.128689  | -0.0903913 |  0.128689  |
+------------+------------+------------+